# Generated by Django 5.0.1 on 2026-02-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREADA', 'Creada'), ('MODIFICADA', 'Modificada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], max_length=15, verbose_name='Acción')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Cambio')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Acción')),
            ],
            options={
                'verbose_name': 'Historial de Reserva',
                'verbose_name_plural': 'Historial de Reservas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha y Hora de Fin')),
                ('proposito', models.CharField(help_text='Breve descripción del propósito', max_length=200, verbose_name='Propósito de la Reunión')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Detallada')),
                ('num_asistentes', models.PositiveIntegerField(help_text='Cantidad de personas que asistirán', verbose_name='Número de Asistentes')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='CONFIRMADA', max_length=15, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
