# Generated by Django 5.0.1 on 2026-02-18 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Área')),
            ],
            options={
                'verbose_name': 'Área/Dependencia',
                'verbose_name_plural': 'Áreas/Dependencias',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area_dependencia',
            field=models.ForeignKey(blank=True, help_text='Seleccione el área o dependencia a la que pertenece', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.area', verbose_name='Área/Dependencia SENA'),
        ),
    ]
