# Generated by Django 5.0.1 on 2026-02-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_area_alter_usuario_area_dependencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('SUPERUSUARIO', 'Super Usuario'), ('OPERATIVO', 'Operativo'), ('CONSULTA', 'Consulta')], default='CONSULTA', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
