# Generated by Django 5.0.1 on 2026-02-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('usuario_intentado', models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario Intentado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('tipo_evento', models.CharField(choices=[('LOGIN_FALLIDO', 'Inicio de Sesión Fallido'), ('ACCESO_DENEGADO', 'Acceso Denegado')], max_length=20, verbose_name='Tipo de Evento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Log de Seguridad',
                'verbose_name_plural': 'Logs de Seguridad',
                'ordering': ['-fecha'],
            },
        ),
    ]
