# Generated by Django 5.0.1 on 2026-02-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Sala')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('capacidad', models.PositiveIntegerField(help_text='Número máximo de personas que puede albergar la sala', verbose_name='Capacidad (personas)')),
                ('ubicacion', models.CharField(help_text='Ejemplo: Edificio A, Piso 2', max_length=150, verbose_name='Ubicación')),
                ('equipamiento', models.TextField(blank=True, help_text='Proyector, videoconferencia, pizarra, etc.', null=True, verbose_name='Equipamiento Disponible')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('MANTENIMIENTO', 'En Mantenimiento'), ('FUERA_SERVICIO', 'Fuera de Servicio')], default='DISPONIBLE', max_length=20, verbose_name='Estado')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='salas/', verbose_name='Imagen de la Sala')),
                ('hora_apertura', models.TimeField(default='07:00', help_text='Hora en que la sala está disponible desde', verbose_name='Hora de Apertura')),
                ('hora_cierre', models.TimeField(default='18:00', help_text='Hora en que la sala cierra', verbose_name='Hora de Cierre')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la sala está activa para reservas', verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nombre'],
            },
        ),
    ]
